<?php

/**
 * @file
 * Legacy Webprofiler module file.
 */

/**
 * Implements hook_theme().
 */
function webprofiler_theme() {
  return array(
    'webprofiler_loader' => array(
      'template' => 'Profiler/webprofiler_loader',
      'variables' => array('token' => NULL, 'profiler_url' => NULL),
    ),
    'webprofiler_toolbar' => array(
      'template' => 'Profiler/webprofiler_toolbar',
      'variables' => array(
        'token' => NULL,
        'templates' => array(),
        'profile' => NULL,
      ),
    ),
    'webprofiler_panel' => array(
      'template' => 'Profiler/webprofiler_panel',
      'variables' => array(
        'template' => array(),
        'token' => NULL,
        'name' => NULL,
      ),
    ),
    'webprofiler_dashboard' => array(
      'template' => 'Profiler/webprofiler_dashboard',
      'variables' => array(
        'profile' => array(),
        'panels' => array(),
        'spinner_path' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_cache_flush().
 */
function webprofiler_cache_flush() {
  $config = \Drupal::configFactory()->get('webprofiler.config');

  if ($config->get('purge_on_cache_clear')) {
    $profiler = \Drupal::service('profiler');
    $profiler->purge();
  }
}
